# 将proxy-providers里面链接中的“你的订阅链接”全部替换即可
mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090


proxy-providers:

  #全部节点
  All:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true"
    interval: 3600
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  #美国节点    
  US:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true&include=(?=.*(美|US|(?i)States|American))"
    interval: 3600
    path: ./us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  #香港节点
  HK:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true&include=(?=.*(港|HK|(?i)Hong))"
    interval: 3600
    path: ./hk.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  #日本节点
  JP:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true&include=(?=.*(日|东京|JP|(?i)Japan))"
    interval: 3600
    path: ./jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204

  #韩国节点
  KR:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true&include=(?=.*(韩|KR|(?i)Korea))"
    interval: 3600
    path: ./kr.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
      
 #台湾节点
  TW:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=你的订阅链接&list=true&udp=true&include=(?=.*(台|湾|TW|(?i)Taiwan))"
    interval: 3600
    path: ./tw.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204


proxies:

            

proxy-groups:
  - name: 手动切换
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Rocket.png
    use:
      - All
    proxies:
      - 自动选择

  - name: 自动选择
    type: url-test
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Auto.png
    use: 
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300
      
  - name: YouTube
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
    proxies:
      - 手动切换
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点
      - DIRECT

  - name: NETFLIX
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netflix.png
    proxies:
      - 手动切换
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点
      - DIRECT

  - name: Disney+
    type: select
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/DisneyPlus.png
    proxies:
      - 手动切换
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点
      - DIRECT

  - name: 巴哈姆特
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bahamut.png
    proxies:
      - 台湾节点
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 手动切换
      - DIRECT

  - name: AdBlock
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Advertising.png
    proxies:
      - REJECT
      - 手动切换

  - name: PayPal
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/PayPal.png
    proxies:
      - DIRECT
      - 手动切换
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点

  - name: 国外网站
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Global.png
    proxies:
      - 手动切换
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点
      - DIRECT

  - name: 苹果服务
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
    proxies:
      - 手动切换
      - DIRECT
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点

  - name: 微软服务
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
    proxies:
      - 手动切换
      - DIRECT
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点

  - name: 网易音乐
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Netease_Music.png
    proxies:
      - DIRECT

  - name: 哔哩哔哩
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/bilibili_3.png
    proxies:
      - DIRECT
      - 手动切换
      - 香港节点
      - 韩国节点
      - 日本节点
      - 美国节点
      - 台湾节点

  - name: 游戏平台
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png
    proxies:
      - 手动切换
      - DIRECT
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点

  - name: 国内网站
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China_Map.png
    proxies:
      - DIRECT
      - 手动切换
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点

  - name: 漏网之鱼
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    proxies:
      - 手动切换
      - DIRECT
      - 香港节点
      - 日本节点
      - 韩国节点
      - 美国节点
      - 台湾节点

  - name: 香港节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    use:
      - HK
    proxies:
      - DIRECT

  - name: 日本节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - JP
    proxies:
      - DIRECT
      
  - name: 韩国节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    use:
      - KR
    proxies:
      - DIRECT
      
  - name: 台湾节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png
    use:
      - TW
    proxies:
      - DIRECT

  - name: 美国节点
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    use:
      - US
    proxies:
      - DIRECT

rule-providers:

  adblock:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite_Classical.yaml"
    path: ./ruleset/Advertising_Classical.yaml
    interval: 86400
        
  YouTube:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400

  Disney:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml"
    path: ./ruleset/Disney.yaml
    interval: 86400

  Bahamut:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bahamut/Bahamut.yaml"
    path: ./ruleset/Bahamut.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400

  Global_Classical:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Global/Global_Classical.yaml"
    path: ./ruleset/Global_Classical.yaml
    interval: 86400



rules:
  - RULE-SET,adblock,AdBlock
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Netflix,NETFLIX
  - RULE-SET,Disney,Disney+
  - RULE-SET,Bahamut,巴哈姆特
  - RULE-SET,Apple,苹果服务
  - RULE-SET,Microsoft,微软服务
  - RULE-SET,NetEaseMusic,网易音乐
  - RULE-SET,BiliBili,哔哩哔哩
  - RULE-SET,Game,游戏平台
  - RULE-SET,Global_Classical,国外网站
  - RULE-SET,China,国内网站
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,国内网站
  - MATCH,漏网之鱼
